import { IsString } from 'class-validator';

export class CreateCoffeeDto {
  @IsString()
  readonly name: string;

  @IsString()
  readonly brand: string;

  @IsString({ each: true })
  readonly flavors: string[];
}
// A great practice with DTOs is to mark all the properties readonly
// this is to help maintain immutability
// why isn't an id necessary? This is something that will most likely be
// generated by the database
// @IsString({ each: true })
// indicates the expected value is an Array of strings
